Multi asset 2
zeitgeistpm/ui pull request #1102
Opened 2023-04-24 09:21 UTC by Robiquet

- Refactor usd price fetching
- Fetch foreign asset metadata
- Support trading of foreign asset based market
- Support Liquidity management
- Support buy/sell full sets
- Fix Market page
- Fix Pool page
- Basic fixes for Portfolio page
- Fix market cards

2023-04-26 17:12 UTC, TvrtkoM requested changes
It seems that everything works except the market card not hiding skeleton for participants and liquidity for markets without a pool

2023-04-27 08:07 UTC, Robiquet commented on components/markets/market-card/index.tsx
> +        {rows.numParticipants != null && rows.baseAsset ? (
Looks like we are fetching base asset from the pool, I'll change it to fetch from the market instead

2023-04-27 08:15 UTC, Robiquet commented on lib/hooks/queries/useMarket.ts
> +        (("marketId" in filter && filter.marketId != null) ||
Looks like this gives a type error 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/4950844/234801800-e1debf9f-099c-4655-ac40-31a73d9a6de5.png">

2023-04-27 08:18 UTC, TvrtkoM commented on lib/hooks/queries/useMarket.ts
> +        (("marketId" in filter && filter.marketId != null) ||
> Looks like this gives a type error

Oh :) didn't think that would happen.

2023-04-27 12:12 UTC, TvrtkoM approved these changes

2023-04-27 12:59 UTC, merged