Scalar util fn for displaying outcomes
zeitgeistpm/ui pull request #1157
Opened 2023-05-05 15:58 UTC by robhyrk

found myself re-using this function so created one that can be shared throughout the app

2023-05-11 08:04 UTC, yornaath requested changes
Looks good, just a couple small changes requested

2023-05-11 08:04 UTC, yornaath commented on lib/util/get-scalar-outcome.ts
> +export const getScalarOutcome = (
I would rename this to `formatScalarOutcome` since its not strictly a getter of the outcome but rather a display formatter.

2023-05-11 08:04 UTC, yornaath commented on components/markets/ScalarPriceRange.tsx
>    const inferedType: ScalarRangeType = scalarType ?? "number";
Do you need to do a null check here since its also done and inferred in the formatting function?

2023-05-22 08:08 UTC, Robiquet approved these changes

2023-06-06 10:44 UTC, yornaath approved these changes

2023-06-07 00:53 UTC, merged