bugfixes
zeitgeistpm/ui pull request #1371
Opened 2023-06-16 11:08 UTC by TvrtkoM

close #1326
close #1314
close #1341

2023-06-16 21:14 UTC, robhyrk commented
There still seems to be an issue with scalar dates. For example `markets/680` shows the correct date (`Jun 12, 2023`) in the `MarketHeader` but the scalar range bar shows `Dec 31, 1969`

2023-06-16 21:31 UTC, TvrtkoM commented
> There still seems to be an issue with scalar dates. For example `markets/680` shows the correct date (`Jun 12, 2023`) in the `MarketHeader` but the scalar range bar shows `Dec 31, 1969`

Can you open a new issue for this? PR contains fixes for three issues mentioned in initial comment.

2023-06-19 15:02 UTC, robhyrk requested changes

2023-06-19 21:42 UTC, robhyrk approved these changes

2023-06-20 00:26 UTC, merged