Update Styles: Full Set modals
zeitgeistpm/ui pull request #1506
Opened 2023-07-05 20:07 UTC by robhyrk

closes #1393

2023-07-11 10:45 UTC, yornaath requested changes
Might need some changes to which address is used when creation extrinsics. Ping @Robiquet

2023-07-11 10:45 UTC, yornaath commented on components/markets/BuyFullSetForm.tsx
> +        .api.tx.balances.transfer(wallet.activeAccount?.address, ZTG.toFixed(0))
@Robiquet When doing transfers using a proxy should we transfer on behalf of `wallet.readlAddress` ?

2023-07-11 10:45 UTC, yornaath commented on components/markets/BuyFullSetForm.tsx
> +    wallet.getActiveSigner()?.address,
Same as above, should we use `wallet.realAddress`? @Robiquet

2023-07-11 10:45 UTC, yornaath commented on components/markets/SellFullSetForm.tsx
> +        .api.tx.balances.transfer(wallet.activeAccount?.address, ZTG.toFixed(0))
@Robiquet Same as the other comments, should we transfer on behalf of `wallet.readAddress` when using proxies?

2023-07-26 15:21 UTC, Robiquet approved these changes

2023-07-26 15:24 UTC, Robiquet commented
Don't think we can merge this without approval from @yornaath. If we don't hear back close and reopen this then I'll approve

2023-08-01 14:50 UTC, closed without merging