Fix: adjust font optimization
zeitgeistpm/ui pull request #1786
Opened 2023-09-11 18:54 UTC by robhyrk

fixes #1785

2023-09-12 08:00 UTC, Robiquet approved these changes

2023-09-12 08:02 UTC, Robiquet requested changes
Sorry... just noticed that fonts aren't loading here (Get started modal). Probably because it's using some sort of portal so that the modal is outside of the element where the fonts were added
<img width="571" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/5fa01697-d6c0-49ff-873f-d757c523f42a">

2023-09-12 08:51 UTC, yornaath requested changes

2023-09-12 08:51 UTC, yornaath commented on layouts/DefaultLayout.tsx
> +      className={`${inter.variable} ${kanit.variable} ${
I would probably put this on the body element in _document. Should fix the issue @Robiquet reported

2023-09-12 18:34 UTC, robhyrk commented
The nextjs docs didn't explain it the best but I found a workaround because for some reason font optimization doesn't load when called in `_document` so I had to add in` _app`, but then there was the issue of not being able to access the `body` tag directly so I ended up adding in the fonts dynamically.

2023-09-14 14:53 UTC, Robiquet commented
I'm still seeing the shifting like we have on staging, I wonder if we can move the modal portal to it get the fonts?

2023-09-19 08:53 UTC, Robiquet approved these changes

2023-10-02 15:05 UTC, yornaath approved these changes

2023-10-03 09:32 UTC, merged