Setting changes
zeitgeistpm/ui pull request #1862
Opened 2023-10-06 11:26 UTC by Robiquet

closes #1675 
closes #1729

2023-10-08 20:37 UTC, robhyrk requested changes

2023-10-08 20:37 UTC, robhyrk commented on components/settings/OtherSettingsForm.tsx
This might be a UX issue: a user can click on `Enable Proxy Execution`, select an account that is not a proxy, uncheck `Enable Proxy Execution`, and then hit save. I suppose this doesn't actually do anything? Maybe you could remove the address input if `Enable Proxy Execution` is not enabled?

2023-10-09 08:44 UTC, Robiquet commented on components/settings/FeePayingAssetSelect.tsx
> +const isSupportedAsset = (id: number) => {
I think it should be filtered as it's not inside `FOREIGN_ASSET_METADATA`

2023-10-09 08:46 UTC, Robiquet commented on components/settings/OtherSettingsForm.tsx
Yeah I'm not sure what the expected behaviour is for this, I'm wondering if we even need the checkbox. Maybe put this as a separate issue and we can discuss?

2023-10-09 14:28 UTC, merged