update next + tailwind
zeitgeistpm/ui pull request #229
Opened 2022-09-07 13:31 UTC by TvrtkoM

2022-09-09 15:18 UTC, Robiquet reviewed
Looks good, do you think there is any risk merging these changes just before launch? Wondering if it's worth holding off for a week

2022-09-09 17:50 UTC, TvrtkoM commented
> Looks good, do you think there is any risk merging these changes just before launch? Wondering if it's worth holding off for a week

Little to no risk to merge, but it's not critical to have and I'm ok with holding it for after launch

2022-09-12 08:14 UTC, Robiquet requested changes
Looks like the fonts aren't loading correctly 
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/4950844/189604945-c018abb8-5912-479d-8053-931812e332a1.png">

2022-09-14 11:38 UTC, Robiquet approved these changes

2022-09-14 14:01 UTC, merged