610 headline comp
zeitgeistpm/ui pull request #676
Opened 2023-02-09 05:12 UTC by robhyrk

- [ ] check why image warning is appearing

2023-02-09 21:56 UTC, robhyrk commented
I wanted to move the MarketImage component into the MarketHeader but nextJS kept throwing a warning. I found more info [here](https://github.com/vercel/next.js/issues/40762); as soon as I moved it back to the main component on that page the warning went away.

2023-02-10 13:35 UTC, Robiquet commented on pages/markets/[marketid].tsx
> +  const prize = prizePool === undefined ? -1 : prizePool ? prizePool : 0;
Can't we use the `undefined` check to see if it's loading rather than setting another value?

2023-02-10 13:42 UTC, Robiquet commented on pages/markets/[marketid].tsx
> +            {new Intl.DateTimeFormat("en-US", {
```suggestion
            {new Intl.DateTimeFormat("default", {
```
Best to get locale dynamically

2023-02-10 13:42 UTC, Robiquet commented on pages/markets/[marketid].tsx
> +  const token = store?.config?.tokenSymbol && store.config.tokenSymbol;
What's the purpose of the additional `&& store.config.tokenSymbol`?

2023-02-10 17:13 UTC, robhyrk commented
Thanks for the feedback! 

I made the changes requested. Some of the conditional checks you pointed out were indeed not necessary so I removed them. I did add a check for subsidy in order to avoid the skeleton rendering infinitely for markets with no liquidity.

2023-02-13 09:42 UTC, Robiquet requested changes
Looks nice! Just one small thing I noticed, I think you need to divide volume by `10**10`. I'm guessing the 'T' stands for trillion
<img width="186" alt="image" src="https://user-images.githubusercontent.com/4950844/218423622-c5afcf2a-f68b-4732-815b-e016eef4cde4.png">

2023-02-13 21:30 UTC, robhyrk commented
> Looks nice! Just one small thing I noticed, I think you need to divide volume by `10**10`. I'm guessing the 'T' stands for trillion <img alt="image" width="186" src="https://user-images.githubusercontent.com/4950844/218423622-c5afcf2a-f68b-4732-815b-e016eef4cde4.png">

Thanks! I was thinking to myself that the volume did seem rather high; I've made the change.

2023-02-14 16:38 UTC, merged