#729 new account drop down
zeitgeistpm/ui pull request #831
Opened 2023-03-09 10:58 UTC by yornaath

Implement the new account button and related dropdown menu as per this selection of components:

https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3622-28991&t=CSD2eGgRYtLjEECn-0

**Alterations:**
Implemented a coming soon label for USDT as @Robiquet noted that this is probably the first stable we will implement.

2023-03-09 16:04 UTC, robhyrk requested changes
Looks great! There is just the hover effect missing when the cursor is above each menu item: https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3622-28991&t=ws6qDnYQrvqd69Y4-0

<img width="209" alt="Screenshot 2023-03-09 at 11 04 12 AM" src="https://user-images.githubusercontent.com/14626415/224082346-b8660d8e-56c0-46d7-b16c-0d619dd378c9.png">

2023-03-09 16:48 UTC, Robiquet reviewed
Don't think the bug was introduced with this pr but do you know what's stopping the modal from closing when clicking outside?

2023-03-09 16:48 UTC, Robiquet commented on components/account/AccountButton.tsx
> +                              Disconnet
```suggestion
                              Disconnect
```

2023-03-10 18:56 UTC, robhyrk approved these changes

2023-03-10 19:01 UTC, robhyrk requested changes
I can't seem to be able to click out of the modal once activated

2023-03-13 10:07 UTC, yornaath commented
> 

This should be fixed in the latest build

2023-03-13 10:17 UTC, Robiquet reviewed
Seems like this is no longer going to it's max width. Probably need to move some css up a level now that `Dialog.panel` is there
<img width="424" alt="image" src="https://user-images.githubusercontent.com/4950844/224672800-7f349bbf-760b-4d1d-b65b-a81777895e6a.png">

2023-03-13 10:19 UTC, Robiquet commented on components/account/OnboardingModal.tsx
> +      headerText="Success on getting a wallet!"
```suggestion
      headerText="Wallet Successfully Installed"
```

2023-03-13 10:19 UTC, Robiquet commented on components/account/OnboardingModal.tsx
> +      bodyText="Now to get ZTG."
```suggestion
      bodyText="Now the last step is to get some ZTG so that you can start trading Prediction Markets!"
```

2023-03-13 10:51 UTC, yornaath commented
> Visit Preview

Ah yeah this should be fixed in the version that is currently building, forgot to commit the last change.
Your copy changes should also be included

2023-03-14 09:23 UTC, merged