Hide market scroll gradient
zeitgeistpm/ui pull request #864
Opened 2023-03-15 21:58 UTC by robhyrk

closes #808 
closes #858 

Also reduced navbar padding as per issue #858

2023-03-16 02:23 UTC, lsaether commented
We can hide it for all screen widths. It's not needed since we have the buttons that show when one reaches the end of the row.

2023-03-17 01:29 UTC, lsaether requested changes
Vertical padding is the y-axis not the x-axis 😄

2023-03-17 16:21 UTC, robhyrk commented
> Vertical padding is the y-axis not the x-axis 😄

Oh dear, lol! I thought that was wrong even after I said it aloud to myself....fixed now!

2023-03-20 11:13 UTC, lsaether approved these changes

2023-03-20 11:13 UTC, merged